/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author santi
 */
public class panelEnviarMensaje extends javax.swing.JPanel {

    /**
     * Creates new form panelEnviarMensaje
     */
    public panelEnviarMensaje(  ) {
        initComponents();
        this.setOpaque(false);
        lblEnviar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        fldMensaje.setOpaque(false);
        fldMensaje.setBackground(new Color(0,0,0,0));
        fldMensaje.setBorder(null);
        fldMensaje.setCaretColor(Color.BLACK);       

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldMensaje = new javax.swing.JTextField(){
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                // No pintar fondo
                if (!isOpaque()) {
                    super.paintComponent(g);
                    return;
                }
                super.paintComponent(g);
            }
        };
        lblEnviar = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fldMensaje.setFont(new java.awt.Font("Nirmala Text", 0, 18)); // NOI18N
        add(fldMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 60));

        lblEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnviarMouseClicked(evt);
            }
        });
        add(lblEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 70, 60));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BoxMensaje.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseClicked
    String texto = fldMensaje.getText();

        if (texto == null || texto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No se puede enviar un mensaje vacío", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            fldMensaje.requestFocus();
            return;
        }

        if (texto.length() > 50) {
            JOptionPane.showMessageDialog(this, 
                "El mensaje es demasiado largo (Máx " + 50 + " caracteres).", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

            
            fldMensaje.setText("");
            fldMensaje.requestFocus(); 
        
    }//GEN-LAST:event_lblEnviarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fldMensaje;
    private javax.swing.JLabel lblEnviar;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
