/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import Objetos.Chat;

/**
 *
 * @author santi
 */
public class PanelChatsDisponibles extends javax.swing.JPanel {

    /**
     * Creates new form PanelChatsDisponibles
     */
    public PanelChatsDisponibles(Chat chat) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUltimoMensaje = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUltimoMensaje.setText("MensajeDefault");
        add(lblUltimoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        lblNombreUsuario.setText("Usuario Default");
        add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoDefault.png"))); // NOI18N
        add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblUltimoMensaje;
    // End of variables declaration//GEN-END:variables
}
